version: "3.9"

#Definition of the services
services:
  mqtt:
    restart: always
    container_name: "mqtt"
    image: eclipse-mosquitto:2.0.8
    environment:
      - MQTTSERVER=mqtt
      - MQTTPORT=1883
      - MOSQUITTO_USERNAME=mqtt
      - MOSQUITTO_PASSWORD=mqtt
      - TZ=Europe/Zurich
    ports:
      - 1883:1883
    volumes:
      - /data/mosquitto:/mosquitto
 
  infopanel:
    restart: always
    tty: true
    container_name: "infopanel"
    image: breiti78/rpi-rgb-led-matrix-infopanel:latest
    privileged: true
    volumes:
     - /data/infopanel:/app/infopanel/config
    command: >
      python3 -m infopanel --config=/app/infopanel/config/infopanel-config.yaml