version: "3.9"

#Definition of the services
services:
  mqtt:
    restart: always
    container_name: "mqtt"
    build: ./mosquitto
    environment:
      - MQTTSERVER=mqtt
      - MQTTPORT=1883
      - MOSQUITTO_USERNAME=mqtt
      - MOSQUITTO_PASSWORD=mqtt
      - TZ=Europe/Zurich
    ports:
      - 1883:1883
    volumes:
      - /data/mosquitto:/mosquitto
 
  infopanel:
    restart: always
    container_name: "infopanel"
    build: ./infopanel
    privileged: true
    volumes:
     - /data/infopanel:/app/infopanel