mqtt:
    broker: localhost
    port: 1883
    client_id: screen
    keepalive: 60
    username: mqtt
    password: mqtt
    topic: anzeigetafel/#

RGBMatrix:
    led-rows: 32
    led-cols: 64
    led-pixel-mapper: U-mapper
    led-chain: 6
    led-parallel: 1
    led-pwm-bits: 11
    led-brightness: 100
    led-gpio-mapping: adafruit-hat-pwm
    led-scan-mode: 1
    led-pwm-lsb-nanoseconds: 130
    led-show-refresh: false
    led-slowdown-gpio: 2
    led-no-hardware-pulse: false

sprites: 
    TextLine1:
        type: DynamicFancyText
        data_label: textline1
        value_color: red
        font_name: 6x13.bdf
    TextLine2:
        type: DynamicFancyText
        data_label: textline2
        font_name: 10x20.bdf
    TimingLine1:
        type: DynamicFancyText
        data_label: line1
        value_color: red
        font_name: 6x13.bdf
    TimingLine2:
        type: DynamicFancyText
        data_label: line2
        font_name: 10x20.bdf
    TimingLine3:
        type: DynamicFancyText
        data_label: line3
        font_name: 10x20.bdf
    TimingLine4:
        type: DynamicFancyText
        data_label: line4
        font_name: 6x12.bdf
        value_color: blue
    TimingLine5:
        type: DynamicFancyText
        data_label: line5
        font_name: 6x12.bdf
        value_color: blue
    scu_logo:
        type: Image
        path: /home/pi/Anzeigetafel/logos/SCU-LOGO.jpg
    altherr_logo:
        type: Image
        path: /home/pi/Anzeigetafel/logos/altherrLogo.png
    ossv_logo:
        type: Image
        path: /home/pi/Anzeigetafel/logos/OSSVLogo.png
    applause:
        type: AnimatedGif
        path: /home/pi/Anzeigetafel/logos/applaus.gif
scenes:
    applause:
        sprites:
        - applause:
    scu_logo:
        sprites:
        - scu_logo:
    altherr_logo:
        sprites:
        - altherr_logo:
    ossv_logo:
        sprites:
        - ossv_logo:
    welcome:
        type: Welcome
    dynamictext:
        sprites:
        - TextLine1:
            x: 3
            y: 10 
        - TextLine2:
            x: 0
            y: 42 
    time: 
        type: Time
    timing: 
        sprites:
        - TimingLine1:
            x: 3
            y: 10
        - TimingLine2:
            x: 0
            y: 26
        - TimingLine3:
            x: 0
            y: 42
        - TimingLine4:
            x: 0
            y: 54
        - TimingLine5:
            x: 0
            y: 63
modes: 
    applause:
    - applause:
        brightness: 70
        duration: 500  
    welcome:
    - welcome:
        brightness: 70
        duration: 500   
    time: 
    - time:
        brightness: 70
        duration: 500
    logo:
    - scu_logo:
        brightness: 70
        duration: 10
    - altherr_logo:
        brightness: 70
        duration: 10 
    - ossv_logo:
        brightness: 70
        duration: 10 
    - applause:
        brightness: 70
        duration: 10
    dynamictext:
    - dynamictext:
        brightness: 70
        duration: 500 
global:
    font_dir: /data/infopanel/fonts
    default_mode: welcome