mqtt:
    broker: 192.168.1.85
    port: 1883
    client_id: screen
    keepalive: 60
    username: mqtt
    password: mqtt
    topic: anzeigetafel/#

RGBMatrix:
    led-rows: 32
    led-cols: 64
    led-pixel-mapper: U-mapper
    led-chain: 6
    led-parallel: 1
    led-pwm-bits: 11
    led-brightness: 100
    led-gpio-mapping: adafruit-hat-pwm
    led-scan-mode: 1
    led-pwm-lsb-nanoseconds: 130
    led-show-refresh: false
    led-slowdown-gpio: 2
    led-no-hardware-pulse: false

sprites: 
    TextLine1:
        type: DynamicFancyText
        data_label: textline1
        value_color: red
        font_name: 6x13.bdf
    TextLine2:
        type: DynamicFancyText
        data_label: textline2
        font_name: 10x20.bdf
    TextLine3:
        type: DynamicFancyText
        data_label: textline3
        font_name: 10x20.bdf
    TextLine4:
        type: DynamicFancyText
        data_label: textline4
        font_name: 6x12.bdf
        value_color: blue
    TextLine5:
        type: DynamicFancyText
        data_label: textline5
        font_name: 6x12.bdf
        value_color: blue
    TimingLine1:
        type: DynamicFancyText
        data_label: line1
        value_color: red
        font_name: 6x13.bdf
    TimingLine2:
        type: DynamicFancyText
        data_label: line2
        font_name: 10x20.bdf
    TimingLine3:
        type: DynamicFancyText
        data_label: line3
        font_name: 10x20.bdf
    TimingLine4:
        type: DynamicFancyText
        data_label: line4
        font_name: 6x12.bdf
        value_color: blue
    TimingLine5:
        type: DynamicFancyText
        data_label: line5
        font_name: 6x12.bdf
        value_color: blue
    scu_logo:
        type: Image
        path: /data/infopanel/logos/SCU-LOGO.jpg
    altherr_logo:
        type: Image
        path: /data/infopanel/logos/altherrLogo.png
    ossv_logo:
        type: Image
        path: /data/infopanel/logos/OSSVLogo.png
    applause:
        type: AnimatedGif
        path: /data/infopanel/logos/applaus.gif
scenes:
    scn-applause:
        sprites:
        - applause:
    scn-scu_logo:
        sprites:
        - scu_logo:
    scn-altherr_logo:
        sprites:
        - altherr_logo:
    scn-ossv_logo:
        sprites:
        - ossv_logo:
    scn-welcome:
        type: Welcome
    scn-time: 
        type: Time
        sprites:
        - TimingLine1:
           x: 3
           y: 10
    scn-blank: 
        type: Blank
    scn-timing: 
        sprites:
        - TimingLine1:
            x: 3
            y: 10
        - TimingLine2:
            x: 0
            y: 26
        - TimingLine3:
            x: 0
            y: 42
        - TimingLine4:
            x: 0
            y: 54
        - TimingLine5:
            x: 0
            y: 63
    scn-text: 
        sprites:
        - TextLine1:
            x: 3
            y: 10
        - TextLine2:
            x: 0
            y: 26
        - TextLine3:
            x: 0
            y: 42
        - TextLine4:
            x: 0
            y: 54
        - TextLine5:
            x: 0
            y: 63
modes: 
    md-applause:
    - scn-applause:
        brightness: 70
        duration: 500  
    md-welcome:
    - scn-welcome:
        duration: 2
    md-time: 
    - scn-time:
        brightness: 70
        duration: 500
    md-logo:
    - scn-scu_logo:
        brightness: 70
        duration: 10
    - scn-altherr_logo:
        brightness: 70
        duration: 10 
    - scn-ossv_logo:
        brightness: 70
        duration: 10 
    - scn-applause:
        brightness: 70
        duration: 10 
global:
    font_dir: /data/infopanel/fonts
    default_mode: md-welcome